### ISSUE TITLE
Something (likely another mod) has attempted to modify the world's state from the wrong thread!

### ISSUE THREAD

**Issue by EasyThe** [jellysquid3/Phosphor#14]
JourneyMap problem I guess?
The stacktrace:
`[23:59:58] [JM-task-4/WARN] [Phosphor]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 71), but was accessed from thread 'JM-task-4' (ID: 132)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:201) [LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:180) [LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:1789) [axw.class:?]
	at journeymap.client.model.ChunkMD.getSavedLightValue(ChunkMD.java:155) [ChunkMD.class:1.12.2-5.5.3]
	at journeymap.client.cartography.Stratum.set(Stratum.java:72) [Stratum.class:1.12.2-5.5.3]
	at journeymap.client.cartography.Strata.push(Strata.java:154) [Strata.class:1.12.2-5.5.3]
	at journeymap.client.cartography.Strata.push(Strata.java:136) [Strata.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.SurfaceRenderer.buildStrata(SurfaceRenderer.java:344) [SurfaceRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.SurfaceRenderer.renderSurface(SurfaceRenderer.java:188) [SurfaceRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:113) [SurfaceRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.SurfaceRenderer.render(SurfaceRenderer.java:86) [SurfaceRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:140) [ChunkRenderController.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:122) [BaseMapTask.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72) [TaskBatch.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416) [MapPlayerTask$MapPlayerTaskBatch.class:1.12.2-5.5.3]
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78) [RunnableTask$Inner.class:1.12.2-5.5.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
`
debug.log on OneDrive because 10MB+
https://1drv.ms/u/s!AlGyVpMYXIIQiXqHTslAGk0-t25g

**Comment by plaguewolf** [comment]
another datapoint, i guess.

`
[22:41:08] [Client thread/WARN] [Phosphor]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 127), but was accessed from thread 'Client thread' (ID: 1)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:201) [LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:180) [LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.func_177413_a(Chunk.java:1789) [axw.class:?]
	at net.minecraft.world.World.func_175705_a(World.java:836) [amu.class:?]
	at net.minecraft.world.World.func_175626_b(World.java:887) [amu.class:?]
	at net.minecraft.client.particle.Particle.func_189214_a(Particle.java:344) [btf.class:?]
	at com.github.alexthe666.iceandfire.client.particle.ParticlePixieDust.func_189214_a(ParticlePixieDust.java:17) [ParticlePixieDust.class:?]
	at net.minecraft.client.particle.Particle.func_180434_a(Particle.java:189) [btf.class:?]
	at net.minecraft.client.particle.ParticleRedstone.func_180434_a(SourceFile:42) [btk.class:?]
	at net.minecraft.client.particle.ParticleManager.func_78874_a(ParticleManager.java:325) [btg.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1387) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
`

**Comment by jellysquid3** [comment]
The second stacktrace is a result of the Ice and Fire mod (see #6). The mod authors will need to patch the issue.

As for the issue with Journeymap, I am uncertain how to reproduce it as it seemingly does not occur with my installation of Journeymap even though I can't see why it wouldn't. Please see if updating to the latest release of Journeymap (version 5.5.4) resolves the issue.

**Comment by EasyThe** [comment]
But I don't have Ice and Fire in my mods?

**Comment by jellysquid3** [comment]
My email thread didn't make it obvious that two users commented on this issue. My point about Ice and Fire is in response to @plaguewolf.

**Comment by jellysquid3** [comment]
@EasyThe Does this issue still occur after updating to a latest version of JourneyMap?

**Comment by EasyThe** [comment]
No. Looks like updating it fixed the problem.

**Comment by jellysquid3** [comment]
Awesome. :smile: I'll go ahead and close this issue.
