### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by HuaXiY** [jellysquid3/Phosphor#22]
[14:49:03] [main/INFO]: Phosphor has been hooked by Forge, setting up Mixin and plugins

[14:49:03] [main/WARN]: Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.5 was found. The mixin config will not be applied.

Exception in thread "main" org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10

	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)

	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)

	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)

	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)

	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)

	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)

	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:24)

	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:11)

	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jellysquid3** [comment]
Please upload a full client debug log. There is not enough information from this stacktrace to determine the issue.

**Comment by HuaXiY** [comment]
> 请上传完整的客户端调试日志。此堆栈跟踪中没有足够的信息来确定问题。
here
[latest.log](https://github.com/jellysquid3/Phosphor/files/3277233/latest.log)

**Comment by HuaXiY** [comment]
there was only one
![TIM截图20190611232053](https://user-images.githubusercontent.com/45794248/59284884-9fc9c500-8c9f-11e9-8627-35c899a291ce.png)

**Comment by jellysquid3** [comment]
LiteLoader is providing an old version of Sponge Mixins, which we require a newer version of. As LiteLoader has not been updated in almost two years, it is very unlikely this issue will ever be resolved with LiteLoader. There is nothing I can do about the issue. You'll have to either remove LiteLoader or remove Phosphor.

**Comment by HuaXiY** [comment]
> LiteLoader提供旧版本的Sponge Mixins，我们需要更新版本。由于LiteLoader近两年没有更新，因此LiteLoader不太可能解决这个问题。关于这个问题我无能为力。您必须删除LiteLoader或删除Phosphor。

oh thanks your answer

**Comment by HuaXiY** [comment]
but······i unload LiteLoader,as before not run.....
