### ISSUE TITLE
Freeze on saving world / entering nether portal

### ISSUE THREAD

**Issue by SakiiCode** [jellysquid3/Phosphor#24]
```
[13:19:49] [JM-task-13/WARN]: Something (likely another mod) has attempted to modify the world's state from the wrong thread!
This is *bad practice* and can cause severe issues in your game. Phosphor has done as best as it can to mitigate this violation, but it may negatively impact performance or introduce stalls.
In a future release, this violation may result in a hard crash instead of the current soft warning. You should report this issue to our issue tracker with the following stacktrace information.
(If you are aware you have misbehaving mods and cannot resolve this issue, you can safely disable this warning by setting `enable_illegal_thread_access_warnings` to `false` in Phosphor's configuration file for the time being.)
java.lang.IllegalAccessException: World is owned by 'Server thread' (ID: 125), but was accessed from thread 'JM-task-13' (ID: 141)
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.acquireLock(LightingEngine.java:204) [LightingEngine.class:?]
	at me.jellysquid.mods.phosphor.mod.world.lighting.LightingEngine.processLightUpdatesForType(LightingEngine.java:185) [LightingEngine.class:?]
	at net.minecraft.world.chunk.Chunk.getLightFor(Chunk.java:1789) [axw.class:?]
	at journeymap.client.model.ChunkMD.getSavedLightValue(ChunkMD.java:155) [ChunkMD.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.NetherRenderer.getSliceLightLevel(NetherRenderer.java:118) [NetherRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.CaveRenderer.buildStrata(CaveRenderer.java:289) [CaveRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.CaveRenderer.renderUnderground(CaveRenderer.java:216) [CaveRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.render.CaveRenderer.render(CaveRenderer.java:127) [CaveRenderer.class:1.12.2-5.5.3]
	at journeymap.client.cartography.ChunkRenderController.renderChunk(ChunkRenderController.java:105) [ChunkRenderController.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.BaseMapTask.performTask(BaseMapTask.java:122) [BaseMapTask.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.TaskBatch.performTask(TaskBatch.java:72) [TaskBatch.class:1.12.2-5.5.3]
	at journeymap.client.task.multi.MapPlayerTask$MapPlayerTaskBatch.performTask(MapPlayerTask.java:416) [MapPlayerTask$MapPlayerTaskBatch.class:1.12.2-5.5.3]
	at journeymap.client.thread.RunnableTask$Inner.run(RunnableTask.java:78) [RunnableTask$Inner.class:1.12.2-5.5.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_51]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

Version 0.2.4,  FTB Continuum modpack
No crash, just loading screen indefinitely

**Comment by jellysquid3** [comment]
Can you upload a client debug log, or otherwise specify the version of JourneyMap you are using?

**Comment by SakiiCode** [comment]
This is the end of the log: https://pastebin.com/eXy47kBW

I'm using JourneyMap 5.5.3 and I assume this is the issue behind random huge lag spikes during gameplay

**Comment by SakiiCode** [comment]
Oh now I see it's Duplicate of #14
