### ISSUE TITLE
Mixin outdated

### ISSUE THREAD

**Issue by awbuckst11181999** [jellysquid3/Phosphor#51]
[11:26:31] [main/DEBUG] [Phosphor Forge Core]: Success! Phosphor has been called into from Forge... initializing Mixin environment and configurations
[11:26:31] [main/WARN] [mixin]: Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied.
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:92)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:79)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:24)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:11)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.inject(MixinPlatformAgentFML.java:307)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:124)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:203)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:196)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[11:26:31] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Trying to install Davinci's Vessels and it only works without Phosphor. It looks like it's because it requires a newer version of mixin?

**Comment by awbuckst11181999** [comment]
My bad, it was another mod.

**Comment by ThePwnd** [comment]
What was the other mod?  I ask because I'm getting a very similar crash log as you were, and I've definitely isolated the problem to just Phosphor and Davinci's Vessels being installed.  Also, there's [a similar bug report](https://github.com/TridentMC/DavincisVessels/issues/301) on the DV GitHub.
