### ISSUE TITLE
requires mixin subsystem version 0.7.10 but 0.7.4 was found

### ISSUE THREAD

**Issue by NitroStarman** [jellysquid3/Phosphor#55]
"Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied."

Never encountered this before and I don't know what it is. My google searches give me nothing useful on this.
Game crashes immediately when trying to launch it. Removing Phosphor mod allows game to launch without issue.
Full log below. I bolded and italicized the 2 lines that stuck out to me. They are towards the bottom of the log.

MultiMC version: 0.6.7-1375
Minecraft folder is:
C:/Users/acbes/Desktop/MultiMC/instances/1.12.2 Survive Nature/minecraft
Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is version 1.8.0_221, using 64-bit architecture.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/acbes/Desktop/MultiMC/instances/1.12.2 Survive Nature/natives

Libraries:
  C:/Users/acbes/Desktop/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2831/forge-1.12.2-14.23.5.2831-universal.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/minecraft/1.12.2/minecraft-1.12.2-client.jar

Native libraries:
  C:/Users/acbes/Desktop/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/acbes/Desktop/MultiMC/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3-natives-windows.jar

Mods:
  [✔️] [1.12]MoVillages-1.5.4
  [✔️] Aquaculture-1.12.2-1.6.8
  [✔️] AutoRegLib-1.3-32
  [✔️] backpack-3.0.2-1.12.2
  [✔️] Baubles-1.12-1.5.2
  [✔️] BaublesHud-1.12.2-5.0.2
  [✔️] better_survival-1.3.6
  [✔️] bettercaves-1.12.2-1.6.0
  [✔️] BetterDiving-1.12.2-1.4.04
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2441-universal
  [✔️] BirdsNests1.12.2-2.1.0
  [✔️] CarryOn MC1.12.2 v1.12.1
  [✔️] CaveExpansionV1.5
  [✔️] Cavern_1.12.2-v2.2.0
  [✔️] caveroot-1.1.1
  [✔️] cfm-6.3.0-mc1.12.2
  [✔️] Chameleon-1.12-4.1.3
  [✔️] colytra-1.12.2-1.2.0.4
  [✔️] comforts-1.12.2-1.4.1.2
  [✔️] conarm-1.12.2-1.2.5.3
  [✔️] CoralReef-2.5-1.12.2
  [✔️] coroutil-1.12.1-1.2.32
  [✔️] craftablechainmail-1.0
  [✔️] CraftableHorseArmour-1.3.0-1.12
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] DenseMetals-1.12.2-2.0.0.30
  [✔️] DoggyTalents-1.12.2-1.15.1.4-universal
  [✔️] DrCyanosLootableBodies_1.12-2.4.0
  [✔️] Durability Show-1.12-5.0.0
  [✔️] DynamicSurroundings-1.12.2-3.4.9.14
  [✔️] ElectroblobsWizardry-4.2.5-MC1.12.2
  [✔️] EnhancedVisuals_v1.2.7_mc1.12.2
  [✔️] extraalchemy-0.5.2
  [✔️] EyesInTheDarkness-0.0.5
  [✔️] FamiliarFauna-1.12.2-1.0.11
  [✔️] foamfix-0.10.9-1.12.2
  [✔️] GottschCore-mc1.12.2-f14.23.5.2768-v1.8.0
  [✔️] grapplemod-v11.1-1.12.2
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] ImmersiveEngineering-0.12-92
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.11.0.212
  [✔️] journeymap-1.12.2-5.5.2
  [✔️] JustAFewFish-1.7_for_1.12
  [✔️] kjlib-1.0.4
  [✔️] LibraryEx-1.12.2-1.0.12
  [✔️] llibrary-1.7.19-1.12.2
  [✔️] malisiscore-1.12.2-6.4.0
  [✔️] malisisdoors-1.12.2-7.3.0
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] MCA-1.12.2-6.1.0-universal
  [📁] memory_repo (folder)
  [✔️] minerva-library-1.0.13
  [✔️] mowziesmobs-1.5.4
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] NetherEx-1.12.2-2.0.15
  [✔️] OptiFine_1.12.2_HD_U_E3
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] PotionFingers-r1.0-2
  [✔️] Quark-r1.6-177
  [✔️] rats-3.2.4
  [✔️] RoguelikeDungeons-1.12.2-1.8.0
  [✔️] Ruins-1.12.2
  [✔️] SereneSeasons-1.12.2-1.2.18-universal
  [✔️] SnowRealMagic-0.3.3
  [✔️] Sound-Physics-1.12.2
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.1
  [✔️] StorageDrawers-1.12.2-5.4.0
  [✔️] StorageDrawersExtras-1.12-3.1.0
  [✔️] TConstruct-1.12.2-2.13.0.171
  [✔️] themidnight-0.3.5
  [📁] treasure2 (folder)
  [✔️] Treasure2-mc1.12.2-f14.23.4.2705-beta0.9.0
  [✔️] TreeChopper-1.12.2-1.2.4
  [✔️] Trinkets and Baubles-1.12.2-0.25.1
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] Wawla-1.12.2-2.5.257
  [✔️] Waystones_1.12.2-4.0.67
  [✔️] weather2-1.12.1-2.6.12

Params:
  --username  --version MultiMC5 --gameDir C:/Users/acbes/Desktop/MultiMC/instances/1.12.2 Survive Nature/minecraft --assetsDir C:/Users/acbes/Desktop/MultiMC/assets --assetIndex 1.12 --uuid  --accessToken  --userType  --versionType release --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1012m, -Xmx5096m, -Duser.language=en]

Minecraft process ID: 17496

Using onesix launcher.

[14:26:29] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:26:29] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:26:29] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:26:29] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2831 for Minecraft 1.12.2 loading
[14:26:29] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_221, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_221
[14:26:29] [main/INFO] [FML]: Searching C:\Users\acbes\Desktop\MultiMC\instances\1.12.2 Survive Nature\minecraft\mods for mods
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in colytra-1.12.2-1.2.0.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod c4.colytra.asm.ColytraLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in DynamicSurroundings-1.12.2-3.4.9.14.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod org.blockartistry.DynSurround.asm.TransformLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in foamfix-0.10.9-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod pl.asie.foamfix.coremod.FoamFixCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:29] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:29] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!
[14:26:29] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from malisiscore-1.12.2-6.4.0.jar
[14:26:29] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_E3.jar
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-177.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in rats-3.2.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in SereneSeasons-1.12.2-1.2.18-universal.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod sereneseasons.asm.SSLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:29] [main/WARN] [FML]: The coremod SSLoadingPlugin (sereneseasons.asm.SSLoadingPlugin) is not signed!
[14:26:29] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Sound-Physics-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:29] [main/WARN] [FML]: The coremod CoreModLoader (com.sonicether.soundphysics.CoreModLoader) is not signed!
[14:26:29] [main/WARN] [FML]: The coremod blusunrize.immersiveengineering.common.asm.IELoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:30] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.6+build50-universal.jar
[14:26:30] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in themidnight-0.3.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:26:30] [main/WARN] [FML]: The coremod midnight (com.mushroom.midnight.core.MidnightLoadingPlugin) is not signed!
[14:26:30] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:26:30] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[14:26:30] [main/INFO] [mixin]: SpongePowered MIXIN Subsystem Version=0.7.4 Source=file:/C:/Users/acbes/Desktop/MultiMC/instances/1.12.2%20Survive%20Nature/minecraft/mods/malisiscore-1.12.2-6.4.0.jar Service=LaunchWrapper Env=CLIENT
[14:26:30] [main/WARN] [FML]: The coremod net.malisis.core.asm.MalisisCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[14:26:30] [main/WARN] [FML]: The coremod MalisisCorePlugin (net.malisis.core.asm.MalisisCorePlugin) is not signed!
[14:26:30] [main/INFO] [mixin]: Compatibility level set to JAVA_8
[14:26:30] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[14:26:30] [main/WARN] [LaunchWrapper]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[14:26:30] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:26:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:26:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:26:30] [main/INFO] [LaunchWrapper]: Calling tweak class optifine.OptiFineForgeTweaker
[14:26:30] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[14:26:30] [main/INFO] [STDOUT]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[14:26:30] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[14:26:30] [main/INFO] [STDOUT]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: C:\Users\acbes\Desktop\MultiMC\instances\1.12.2 Survive Nature\minecraft\mods\OptiFine_1.12.2_HD_U_E3.jar
[14:26:30] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:26:32] [main/INFO] [FML]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:26:32] [main/INFO] [LaunchWrapper]: Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[14:26:32] [main/INFO] [mixin]: Initialised Mixin FML Remapper Adapter with net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper@4e904fd5
**_[14:26:32] [main/WARN] [mixin]: Mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10 but 0.7.4 was found. The mixin config will not be applied._**
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:199]: Failed to start Minecraft:
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
_**[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Required mixin config mixins.phosphor.json requires mixin subsystem version 0.7.10**_
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.checkVersion(MixinConfig.java:417)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:331)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:894)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:116)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:91)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:78)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:24)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at me.jellysquid.mods.phosphor.core.PhosphorFMLSetupHook.call(PhosphorFMLSetupHook.java:11)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:165)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformAgentFML.inject(MixinPlatformAgentFML.java:317)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinContainer.inject(MixinContainer.java:124)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:203)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:189)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at org.spongepowered.asm.launch.MixinTweaker.injectIntoClassLoader(MixinTweaker.java:62)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:26:32] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[14:26:32] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[14:26:32] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at org.multimc.EntryPoint.main(EntryPoint.java:38)
Exception in thread "main" 
Process exited with code 1.
Clipboard copy at: 23 Dec 2019 15:01:04 -0500

**Comment by ZombieHDGaming** [comment]
Find the more up-to-date version of MalisisCore on the Sponge forums, since the official release uses Mixins 0.7.4 which is extremely outdated at this point, and someone updated it so it is no longer a headache.

**Comment by jellysquid3** [comment]
This is not an issue with Phosphor. You have another mod (MalisisCore) which provides an old version of Sponge Mixins. There is nothing we can do about it.
