### ISSUE TITLE
"WARNING:coremods are present"

### ISSUE THREAD

**Issue by HTXrltd** [jellysquid3/Phosphor#56]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 12/27/19 2:14 PM
Description: Unexpected error

java.lang.NoSuchFieldError: field_191308_b
	at net.optifine.config.ConnectedParser.parseEntities(ConnectedParser.java:1248)
	at net.optifine.shaders.EntityAliases.loadEntityAliases(EntityAliases.java:164)
	at net.optifine.shaders.EntityAliases.update(EntityAliases.java:89)
	at net.optifine.shaders.EntityAliases.resourcesReloaded(EntityAliases.java:61)
	at net.optifine.shaders.Shaders.resourcesReloaded(Shaders.java:5917)
	at net.optifine.util.TextureUtils.resourcesReloaded(TextureUtils.java:321)
	at net.optifine.util.TextureUtils$1.func_110549_a(TextureUtils.java:362)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at net.optifine.util.TextureUtils.registerResourceListener(TextureUtils.java:366)
	at net.minecraft.client.renderer.EntityRenderer.frameInit(EntityRenderer.java:2809)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1307)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jellysquid3** [comment]
There's nothing in this crash log which would indicate Phosphor being at fault. You have likely used a version of OptiFine which is incompatible with the currently installed version of Forge.

**Comment by HTXrltd** [comment]
thanks
